### ISSUE TITLE
Api token

### ISSUE THREAD

**Issue by jmoreno96** [dwave-examples/airline-hubs#7]
Hello!

I would love to use this algorithm for my final master work in aerospace engineering. Using European airports and analyzing different hub networks with different fuel prices. 

I have downloaded the repository but I can't access the dwave systems API, would it be possible to use it?

Thank you very much

**Comment by vgoliber** [comment]
Hi @jmoreno96 - you'll need to have a Leap account to run this example. You can sign up for an account here: https://cloud.dwavesys.com/leap/signup/.
 
In your Leap account, you can get an API token which will give you access to the QPU via the SAPI endpoint. There are multiple ways to use your API token and they are all described in the following documentation:  https://docs.ocean.dwavesys.com/en/stable/overview/sapi.html#table-token-config.

Alternatively, you can also run this code without any configurations by using the Leap IDE once you've signed in: https://ide.dwavesys.io/workspaces/.

Hope this helps! Feel free to reach out again if you have more questions.

**Comment by jmoreno96** [comment]
Thanks a lot :) Excellent work by the way!!
